server:
  port: 8200
eureka:
  instance:
    hostname: server2
    instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
        defaultZone: http://server1:8100/eureka,http://server3:8300/eureka
